services:
  - type: web
    name: uart-sniffer
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production